/* ============================================================================
   Cor Portal v2 - mindmap renderer.
   Renders window.COR_MINDMAP_MD (generated by scripts/build-mindmap.py from the
   snapshot) as an interactive markmap, Cor-styled, with deep-links into the
   portal surfaces. Vendored libs (d3 + markmap-*) load before this script.

   Load order on mindmap.html:
     vendor/d3 -> vendor/markmap-view -> vendor/markmap-lib ->
     vendor/markmap-toolbar -> js/mindmap-data.js -> js/chrome.js -> js/mindmap.js
   ============================================================================ */
(function () {
  "use strict";
  var M = window.markmap;
  var svg = document.getElementById("markmap");
  var SRC = window.COR_MINDMAP_MD;

  if (!M || !M.Markmap || !M.Transformer || !svg) {
    document.body.insertAdjacentHTML("beforeend",
      '<p style="font-family:var(--mono);color:var(--oxblood);padding:1rem">' +
      "Could not load the map libraries. Keep the <code>vendor/</code> folder beside the site.</p>");
    return;
  }
  if (!SRC) {
    document.body.insertAdjacentHTML("beforeend",
      '<p style="font-family:var(--mono);color:var(--oxblood);padding:1rem">' +
      "Map data unavailable - run <code>scripts/build-snapshot.py</code> then " +
      "<code>scripts/build-mindmap.py</code> to generate it.</p>");
    return;
  }

  var transformer = new M.Transformer();
  var result = transformer.transform(SRC);
  var fm = result.frontmatter || {};
  var mm = M.Markmap.create(svg, M.deriveOptions(fm.markmap), result.root);

  // The pre-render bakes a semantic nested-list fallback (#mindmap-fallback) so
  // no-JS/crawler fetches get the full tree as real links; once the interactive
  // markmap is live it's redundant, so remove it. No-op when absent (dev serve).
  var _mmFallback = document.getElementById("mindmap-fallback");
  if (_mmFallback) _mmFallback.remove();

  // Caption from the generated provenance, so it's honest about what's shown.
  var meta = window.COR_MINDMAP_META || {};
  var built = meta.generated_from_snapshot_built_at;
  var cap = document.querySelector(".mm-caption");
  if (cap) {
    cap.innerHTML = "<b>Cor</b> &#9670; the map - generated from the live snapshot" +
      (built ? ", built " + String(built).replace(/T.*/, "") : "") +
      ". Every node links into the spec.";
  }

  function refit() { return Promise.resolve(mm.setData(result.root)).then(function () { mm.fit(); }); }

  // Spectral / JetBrains Mono load asynchronously; markmap measures node sizes at
  // first render, so before the fonts arrive the tree can collapse onto a point.
  // Re-layout + re-fit once the fonts settle (resolves instantly when cached, and
  // even if a web font fails the fallback serif is then stable).
  if (document.fonts && document.fonts.ready) {
    document.fonts.ready.then(refit);
  }

  // --- Export (SVG keeps vectors; PNG rasterizes at 2x). Both snapshot the
  // current fold state, on the parchment ground, with Cor type/colours. ---
  var SVGNS = "http://www.w3.org/2000/svg";
  function exportBg() {
    var bg = getComputedStyle(document.body).backgroundColor;
    return (!bg || bg === "transparent" || bg === "rgba(0, 0, 0, 0)") ? "#ece0c4" : bg;
  }
  function buildExportSvg() {
    var bb = svg.querySelector("g").getBBox();
    var pad = 24;
    var x = Math.floor(bb.x - pad), y = Math.floor(bb.y - pad);
    var w = Math.ceil(bb.width + pad * 2), h = Math.ceil(bb.height + pad * 2);
    var clone = svg.cloneNode(true);
    clone.removeAttribute("id");
    clone.setAttribute("xmlns", SVGNS);
    clone.setAttribute("width", w);
    clone.setAttribute("height", h);
    clone.setAttribute("viewBox", x + " " + y + " " + w + " " + h);
    var cg = clone.querySelector("g");
    if (cg) cg.removeAttribute("transform");
    var rect = document.createElementNS(SVGNS, "rect");
    rect.setAttribute("x", x); rect.setAttribute("y", y);
    rect.setAttribute("width", w); rect.setAttribute("height", h);
    rect.setAttribute("fill", exportBg());
    clone.insertBefore(rect, clone.firstChild);
    var style = document.createElementNS(SVGNS, "style");
    style.textContent = "text{fill:#4a1e26}foreignObject,foreignObject *{color:#4a1e26;" +
      "font-family:Spectral,Georgia,'Times New Roman',serif}a{fill:#2d6b6b}code{color:#a5801f}";
    clone.insertBefore(style, clone.firstChild);
    return { str: '<?xml version="1.0" encoding="UTF-8"?>\n' + new XMLSerializer().serializeToString(clone), w: w, h: h };
  }
  function triggerDownload(href, name) {
    var a = document.createElement("a");
    a.href = href; a.download = name; a.rel = "noopener";
    document.body.appendChild(a); a.click(); a.remove();
  }
  function exportSvg() {
    var s = buildExportSvg();
    triggerDownload("data:image/svg+xml;charset=utf-8," + encodeURIComponent(s.str), "cor-map.svg");
  }
  function exportPng() {
    var s = buildExportSvg(), scale = 2;
    var img = new Image();
    img.onload = function () {
      var canvas = document.createElement("canvas");
      canvas.width = s.w * scale; canvas.height = s.h * scale;
      var ctx = canvas.getContext("2d");
      ctx.scale(scale, scale);
      ctx.drawImage(img, 0, 0);
      try { triggerDownload(canvas.toDataURL("image/png"), "cor-map.png"); }
      catch (e) { exportSvg(); }
    };
    img.onerror = function () { exportSvg(); };
    img.src = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(s.str);
  }

  function setFold(node, fold) {
    node.payload = Object.assign({}, node.payload, { fold: fold });
    (node.children || []).forEach(function (c) { setFold(c, fold); });
  }
  function rerender() { return Promise.resolve(mm.setData()).then(function () { mm.fit(); }); }

  if (M.Toolbar) {
    var UNFOLD_MORE = "M12 5.83L15.17 9l1.41-1.41L12 3 7.41 7.59 8.83 9 12 5.83zm0 12.34L8.83 15l-1.41 1.41L12 21l4.59-4.59L15.17 15 12 18.17z";
    var UNFOLD_LESS = "M7.41 18.59L8.83 20 12 16.83 15.17 20l1.41-1.41L12 14l-4.59 4.59zm9.18-13.18L15.17 4 12 7.17 8.83 4 7.41 5.41 12 10l4.59-4.59z";
    var ICON_SVG = "M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z";
    var ICON_PNG = "M21 3H3v18h18V3zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z";
    var tb = M.Toolbar.create(mm);
    tb.setBrand(false);
    tb.register({ id: "expandAll", title: "Expand all", content: M.Toolbar.icon(UNFOLD_MORE),
      onClick: function () { setFold(mm.state.data, 0); rerender(); } });
    tb.register({ id: "collapseAll", title: "Collapse all", content: M.Toolbar.icon(UNFOLD_LESS),
      onClick: function () { (mm.state.data.children || []).forEach(function (c) { setFold(c, 1); }); rerender(); } });
    tb.register({ id: "downloadSvg", title: "Download SVG", content: M.Toolbar.icon(ICON_SVG), onClick: exportSvg });
    tb.register({ id: "downloadPng", title: "Download PNG", content: M.Toolbar.icon(ICON_PNG), onClick: exportPng });
    tb.setItems(["zoomIn", "zoomOut", "fit", "expandAll", "collapseAll", "downloadSvg", "downloadPng"]);
    document.body.appendChild(tb.render());
  }
})();
